### ISSUE TITLE
Make test for user non-existence more robust

### ISSUE THREAD

**Issue by chriscohen** [ixis/codeception-module-drupal-user-registry#2]
On my test suite it's going through checking if users already exist before creating them, but it's getting a false positive and failing to create a user that doesn't exist.

DrushTestUserManager::createUser() doesn't have a very robust check on the drush output, which I think might be causing this.

Here's the output of my drush command which is causing the false positive.

```
exception 'Drush\User\UserListException' with message 'Unable to find a matching user for test.news.editor.'  [error]
in /home/vagrant/.composer/vendor/drush/drush/lib/Drush/User/UserList.php:117
Stack trace:
#0 /home/vagrant/.composer/vendor/drush/drush/lib/Drush/User/UserList.php(15):
Drush\User\UserList::getFromParameters('test.news.edito...')
#1 /home/vagrant/.composer/vendor/drush/drush/commands/user/user.drush.inc(248):
Drush\User\UserList->__construct('test.news.edito...')
#2 [internal function]: drush_user_information('test.news.edito...')
#3 /home/vagrant/.composer/vendor/drush/drush/includes/command.inc(359):
call_user_func_array('drush_user_info...', Array)
#4 /home/vagrant/.composer/vendor/drush/drush/includes/command.inc(210): _drush_invoke_hooks(Array, Array)
#5 [internal function]: drush_command('test.news.edito...')
#6 /home/vagrant/.composer/vendor/drush/drush/includes/command.inc(178): call_user_func_array('drush_command',
Array)
#7 /home/vagrant/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(46): drush_dispatch(Array)
#8 /home/vagrant/.composer/vendor/drush/drush/drush.php(76): Drush\Boot\DrupalBoot->bootstrap_and_dispatch()
#9 /home/vagrant/.composer/vendor/drush/drush/drush.php(16): drush_main()
#10 {main}
```

**Comment by dustinleblanc** [comment]
Getting similar verbose debugging output but things seem to run okay:
```
exception 'Drush\User\UserListException' with message 'Unable to find[error]
a matching user for test.administrator.' in
/Users/dustin/.composer/vendor/drush/drush/lib/Drush/User/UserList.php:114
Stack trace:
#0
/Users/dustin/.composer/vendor/drush/drush/lib/Drush/User/UserList.php(15):
Drush\User\UserList::getFromParameters('test.administra...')
#1
/Users/dustin/.composer/vendor/drush/drush/commands/user/user.drush.inc(253):
Drush\User\UserList->__construct('test.administra...')
#2 [internal function]: drush_user_information('test.administra...')
#3
/Users/dustin/.composer/vendor/drush/drush/includes/command.inc(368):
call_user_func_array('drush_user_info...', Array)
#4
/Users/dustin/.composer/vendor/drush/drush/includes/command.inc(219):
_drush_invoke_hooks(Array, Array)
#5 [internal function]: drush_command('test.administra...')
#6
/Users/dustin/.composer/vendor/drush/drush/includes/command.inc(187):
call_user_func_array('drush_command', Array)
#7
/Users/dustin/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62):
drush_dispatch(Array)
#8 /Users/dustin/.composer/vendor/drush/drush/drush.php(70):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 /Users/dustin/.composer/vendor/drush/drush/drush.php(11):
drush_main()
#10 {main}
Creating test user 'test.administrator' on @litehouse_local.test.
Added role administrator role to test.administrator                  [success]
```

Thanks for the great module!

**Comment by dustinleblanc** [comment]
Circling back on this issue @pfaocle @chriscohen; I am using this module for testing a Drupal 8 site and its working great, I'd like to quiet down the noisy output, any ideas on where to attack that?

Thanks!
